### ISSUE TITLE
Logging - `debug`?

### ISSUE THREAD

**Issue by ramontayag** [adomokos/light-service#158]
I find logging quite useful for debugging. When I'm not debugging something it's a bit too verbose. What do you think about logging it in the debug level instead of info?

**Comment by adomokos** [comment]
What do you think about using Logger's levels to adjust that?

Instead of using `.info`, we might just send it to a logger facade, that wraps [log4r](https://github.com/colbygk/log4r) or something similar the user sets up via configuration, and the level could be adjusted by the logging library and not LS.

LightService would send the verbose logs all the time, but the log-level could be adjusted by the logging tool.

What do you think?

**Comment by ramontayag** [comment]
Ah yes -- don't know why I didn't think of this. Thanks!
