### ISSUE TITLE
Testing actions in isolation

### ISSUE THREAD

**Issue by tlowrimore** [adomokos/light-service#191]
Hi @adomokos ,

I am attempting to create unit tests on a per action basis.  I am using the ContextFactory to setup the context for each action under test.  I would like to test each action individually with no dependency upon previous actions in the action chain.  I have run into an issue where setting up the ContextFactory with my organizer, for the action under test, causes all actions in the action chain to be executed.  Is it possible to run an test each action, individually without invoking previous actions in the action chain?

Thanks so much for your help!

**Comment by adomokos** [comment]
Hello @tlowrimore!

Thanks for using LightService.

We created the `ContextFactory` helper for "segmented" outside-in tests. Meaning, when we had 5 actions like this:

```ruby
[Action1,
Action2,
Action3,
Action4,
Action5]
```
and we wanted to test `Action4`,  (we had to have a lot of data in the `Context`, and since we talked to the database anyway as it was fast with [database_cleaner](https://github.com/DatabaseCleaner/database_cleaner) transactions) we just executed the pipeline up-to `Action3`, and used the context in that state at that point in time.

In case you want to call one action in isolation, you can invoke it via the `execute` method.
See [this example] for it(https://github.com/adomokos/light-service/blob/master/spec/action_spec.rb#L65-L69) for it.

The `Context` is a more specific `Hash`, you can initialize it with `LightService::Context.make`, like [in the spec](https://github.com/adomokos/light-service/blob/master/spec/action_spec.rb#L5), and then you can add any items your actions need. Invoke `execute` on your action and assert on the items in the resulting `Context`.

I am thinking this would be a good paragraph in the README. In case someone would contribute with a small README pr.

Hth.

**Comment by tlowrimore** [comment]
@adomokos 

Wow!  Thanks so much for the rapid response!  This is exactly what I was looking for!  I'll give it a go, and once I have a working version, I'd be happy to create a PR for the update to the docs.

Cheers!
Tim

**Comment by gee-forr** [comment]
I had 30 minutes free, so I thought I'd add some docs into the readme about how to run actions in isolation, that led to me turning it into a small "Getting Started" section.

I already have a PR open #194  so I thought I'd sneak it in there, even though it's not strictly related to the PR's content. @tlowrimore, let me know if you'd like me to add anything to the readme. You can see the changes here: 3fe6a63cd8a23dfc2e549593c2faeaf86fb796c8

**Comment by adomokos** [comment]
Seems like @tlowrimore is happy with the response, closing this issue.
